# One-time setup: create deployment (run after first model is registered)
# az ml online-deployment create -f training/online_deployment.yml -g mlops-wsh-rg-1 -w mlops-workspace --all-traffic
$schema: https://azuremlschemas.azureedge.net/latest.onlineDeployment.schema.json
name: blue
endpoint_name: nlp-sentiment-endpoint

model: azureml:nlp-sentiment-model@latest

environment:
  conda_file: ../conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

code_configuration:
  code: ../src
  scoring_script: score.py

instance_type: Standard_DS2_v2
instance_count: 1
request_settings:
  request_timeout_ms: 30000
